---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app comfy-proxy
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      *app :
        containers:
          app:
            image:
              repository: docker.io/library/nginx
              tag: 1.29.4@sha256:ca871a86d45a3ec6864dc45f014b11fe626145569ef0e74deaffc95a3b15b430

            env:
              TZ: ${TIMEZONE}
              PORT: &port 80

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }

            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 1Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    route:
      app:
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        hostnames: ["{{ .Release.Name }}.${PRIVATE_DOMAIN}"]
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      config-file:
        enabled: true
        type: configMap
        name: comfy-proxy-config
        globalMounts:
          - path: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
      tmpfs:
        type: emptyDir
        advancedMounts:
          *app :
            app:
              - path: /var/cache/nginx/client_temp
                subPath: client_temp
