---
apiVersion: v1
kind: Service
metadata:
  name: comfyui-backend
spec:
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: comfyui-backend
subsets:
  - addresses:
      - ip: 10.0.0.189
    ports:
      - port: 8188