---
apiVersion: v1
kind: Service
metadata:
  name: nginx-comfyui-proxy
  labels:
    app: nginx-comfyui-proxy
spec:
  type: LoadBalancer
  selector:
    app: nginx-comfyui-proxy
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: comfyui-backend
  namespace: default
spec:
  type: ExternalName
  externalName: 10.0.0.189
  ports:
  - name: http
    port: 8188
    targetPort: 8188
    protocol: TCP