apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    PRIVATE_DOMAIN: ENC[AES256_GCM,data:7WteA9GuXzy9LU1l,iv:oV2Kb5znVYtXPAcNLdZJ0FL7aP1fqDCQg3pgXnFF7bU=,tag:eNyuZ/LYhwymQ0QP7cDh1A==,type:str]
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:Hw2XV4qyFM6Jm74O,iv:URQfKn41s/dbIfpVly23rtBcp1AqlE0HUt2Ysairevk=,tag:p5iiV9qtdDy8ly22YOLEMA==,type:str]
sops:
    age:
        - recipient: age17wezhckaqyhyxud66fq5ckra06h3837p4uzqemymn9cjspq9eshq0eyf0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESi9Zem1NNlBRbFpRTHZZ
            L2RvNWZaKzNRMmFqeUdWOEFHd3pzeTVMYkdFClp6OUdxRUU3Q1lINWJneDVpency
            dkVIZ2ZHbndFVHFPTHJ6SEYrdlBmOFEKLS0tIFFkTXgvRVJLY3JMRm94RkhpQVBw
            SENwTm0vYXNJdVVlOUJISlRqM1hWZW8KJ8qaTTTSEghg99/SI86OPAtL1jlSN5sJ
            Hu2KoB8nZFodZEEHmM7IWOH/Vno8nwbeMqhuRnnVv5Qqo9Sn6hPIPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-05T15:30:50Z"
    mac: ENC[AES256_GCM,data:FvDMF435/kI55rUZR0VTkNt405I3uv+gr5AvDWctqhx0+WTEWmlKgO4SPCQWW8DMd5nP/CfpO9/uupxO8AH+b04iNwviXB5+fw3m393R8NGKrPXWsUAhD5hV9DQUjGurAVlwJprAq6j6tbPXIXe9uwM4jx5zoBYkJQ6eXYBraJU=,iv:2U009QxiapW2XQHBKY+MqAEkAp0j6oc9IWHcYUA+Vnw=,tag:Ped3dQnE2cf+/I6Bdn2LdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
