---
apiVersion: v1
kind: Service
metadata:
  name: comfy
spec:
  type: ExternalName
  externalName: 10.0.0.189
  ports:
    - name: http
      port: 80
      targetPort: 8818
      protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: comfy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: cilium
    cilium.io/ingress-proxy-protocol: "off"   
spec:
  ingressClassName: cilium
  tls:
    - hosts:
        - "comfy.${PRIVATE_DOMAIN}"
      secretName: "${PRIVATE_DOMAIN/./-}-production"
  rules:
    - host: comfy.${PRIVATE_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: comfy
                port:
                  number: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: comfy
  namespace: ai
spec:
  parentRefs:
    - name: comfy
  hostnames:
    - comfy.${PRIVATE_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: comfy-api-service
          port: 8188

    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: comfy-frontend
          port: 80