---
apiVersion: v1
kind: Service
metadata:
  name: comfy
spec:
  ports:
  - name: https
    port: 8188
    targetPort: 8188
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: comfy-1
  labels:
    kubernetes.io/service-name: comfy
addressType: IPv4
ports:
  - name: ''
    appProtocol: http
    protocol: TCP
    port: 8188
endpoints:
  - addresses:
      - "10.0.0.189"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: comfy
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
  - hosts:
    - "comfy.${PRIVATE_DOMAIN}"
    secretName: tls-external-service
  rules:
  - host: "comfy.${PRIVATE_DOMAIN}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: comfy
            port:
              number: 8188