---
apiVersion: v1
kind: Service
metadata:
  name: comfy
spec:
  ports:
  - name: app
    port: 80
    protocol: TCP
    targetPort: 8188
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: comfy
subsets:
- addresses:
  - ip: 10.0.0.189
  ports:
  - name: app
    port: 8188
    protocol: TCP