apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
    namespace: flux-system
stringData:
    TEST_KEY: ENC[AES256_GCM,data:kHwWJtwdNQA=,iv:DEfkU1asWxDz1tvK+QX8NTfd6zq4z7Vl3uoZxWiNV+w=,tag:kwqU08qil69eyp5fGro9Eg==,type:str]
sops:
    age:
        - recipient: age17wezhckaqyhyxud66fq5ckra06h3837p4uzqemymn9cjspq9eshq0eyf0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESi9Zem1NNlBRbFpRTHZZ
            L2RvNWZaKzNRMmFqeUdWOEFHd3pzeTVMYkdFClp6OUdxRUU3Q1lINWJneDVpency
            dkVIZ2ZHbndFVHFPTHJ6SEYrdlBmOFEKLS0tIFFkTXgvRVJLY3JMRm94RkhpQVBw
            SENwTm0vYXNJdVVlOUJISlRqM1hWZW8KJ8qaTTTSEghg99/SI86OPAtL1jlSN5sJ
            Hu2KoB8nZFodZEEHmM7IWOH/Vno8nwbeMqhuRnnVv5Qqo9Sn6hPIPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-06T22:13:09Z"
    mac: ENC[AES256_GCM,data:sQvHSgao2eAk4qJpoXqoqd5vIzYVqDRbVsefFFw2gbh0PgNmlY2az/eaVgl1XHXOArh9wAcjvUGIdvWndAWpbpoG05h1JgSfWcV7bLARZedqkx6SLzA2kx28ODtDZ5pjRLJhP7MFC9VGiL/pWTemlmEaBzw5OY++lFb9E2L8CNk=,iv:wruD7nHF5Xls2/BeV8xhH0nRwtk//CUSQaMR8fOSwT4=,tag:FoWt7rfg1/jP+d7aTOP1qw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
